### ISSUE TITLE
Epic: A grid input for quickly creating new stub student records

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/Student-Registration-React-Web#64]
### Organization Need
Students and Coaches should face no obstacle to participation and sessions, and Coaches have to start tracking attendance immediately somehow. Most resort to a combination of paper and memory until the student record has been set up in Salesforce for access on the Coach app.
This need is specific to shortening that wait.
Just like paper, the coach needs the ability to jot down limited information and start tracking that student's attendance immediately

### Proposed Solution
A grid view that is an option on the Student Registration App, in the Flow for Coaches supporting:
- [ ] quick entry of First, Last Names, School Attending
- [ ] Optional: Parent Phone, Parent Email
- [ ] Optional: Team Season (Creates Enrollment Record. This can also be done in the Coach App)
- [ ] Accessible/Usable on a desktop browser but also mobile Web

### Considerations
- [ ] There is a potential for duplications and need for QA solutions. A field may need to be added or way to identify a Stub Record to avoid conflict with duplicate management rules in Salesforce
- [ ] We will likely need to experiment with required fields and adding/removing fields
- [ ] [Users are likely to copy-paste from various sources such as web sheets, Office documents, text files, so ideally they should have to perform no cleanup and delimiters, spaces, should just work. ](https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/issues/92)
- [ ] Coordination with Salesforce development will be important during testing and rollout to manage duplicate rule dependencies and other flow automation such as summary for Regional Program Managers or welcome email/text to Parent/Guardians

### Potential Resources
https://github.com/silevis/reactgrid

### Proposed Design
1. User can choose to switch to enrollment at any time in the Coach Flow
2. The first column allows the user to search for a student by name
3. The user selects a program site in the second column
4. The user selects a team season in the third column
5. The user can commit at any time and the rows with (verified) committed values become read-only
6. New rows are provided for additional entries

#### Considerations

- Players could be multi-enrolled in this scenario. Some validation may be employed later
- It may be helpful to provide a season selector at the top. Default would be the present season based on date
- Error messages from salesforce should be presented in a modal so they can be copied and shared with Support
- To make Search efficient, recommendation is to load the entire directory of students, school (Account Name), and Grade Level, ordered by Create Date (most recent first), and present these details in a results selector

![Image](https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/assets/1458369/1bb694d1-fd33-42ab-aab3-eb002e27e6b5)

#### Search Example

![Image](https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/assets/1458369/91f7b656-37ce-45f7-bdb7-e6cb479919a5)

### API Requirement
- Create and return StudentID to support Enrollment record creation (one or many?)
- Create one or many enrollment records
- Return TeamSeason names and ID's based on School Site (Account) Selection

**Comment by CritiqalPete** [comment]
At MVP we will allow for duplicate student records to be created so no check is needed. I also suggest we hold off the Search feature initially.

**Comment by CritiqalPete** [comment]
let's deploy with this workflow first and then see about the need and ideal UX to include search and reducing duplicates for returing students.

**Comment by za-zohaib** [comment]
Sounds good, Will start working on it

**Comment by CritiqalPete** [comment]
### more thinking about initial implementation (@za-zohaib) :
**Enroll Students Grid API:**
Any student name = yes. The UX calls for a "search" to support finding. If you can emulate the search examples in the Student Registration app (that only Coaches can access) or the Search in the Coach Mobile app, that's great. A fallback might be to try loading a list of student names and ID's to search, scoped by Region. The Region should already by associated with the Coach Record.

**School/Site:**
Appears in a Dropdown, filtered by the Region (this School/site object is Account)

**Team-Season:**
Shows the Team_Season list associated to the selected School/Site. Eventually this will be scoped to the current Season and Previous. E.g. on June 7 2024 we would include "2023-2024" and "2024 Summer"

** If the student has been Selected via search**
POST an Enrollment Record to Enrollments with Student (Contact) ID, Team_Season ID, Start

**Comment by CritiqalPete** [comment]
testing questions

- [ ] verify all the school sites are provided in the filtering from region (API)
- [ ] UI remains visible at all times when updating selectors
- [ ] Once some records are submitted, the section is collapsed with the name of the region and season
- [ ] Reload "warns" the user about lost data
- [ ] Can submit records and "IsIncomplete" is set to TRUE on Salesforce (API)
- [ ] If there is an Error from the API/Salesforce a message appears "There appears to be a problem with the selected Site and/or Team Season. Please try another or inform your Program Manager about this."

**Comment by CritiqalPete** [comment]
i will make tickets for some of the feature additions listed. This ticket has become an epic.

- [ ] Mobile Support: Im not sure what this should look like. Needs design, since grids are not very amenable to mobile UI/UX
- [ ] copy-paste spreadsheet style input. I know this is a whole new component, like reactgrid.
- [ ] The accordion behavior being worked on is significant enough to track
