### ISSUE TITLE
(Epic) Identify a method to monitor and alert for fails and error continuously.

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/Student-Registration-React-Web#68]
### Problem Statement
The Registration App has a critical role to play in the legal and formal connection between guardians/parents and SCORES.
Accessibility as well underlying complexity lead to unknown downtimes and inadvertent loss of users.

We need to build trust with users and Coaches at all levels of the UX.

### Proposed Solution
Alerting to issues will require identifying types of "showstopper" problems users encounter and monitoring for these will improve our understanding.

_This task is to propose a solution for monitoring that will work with the other areas of action and dependency_

### Related Areas of Action

- [ ] Analytics-- Are we getting the most important events? Can they demonstrate critical and major problems as well as completion rates? What needs to be added?
- [ ] Server logging -- do we need to monitor for errors at the server or API level? Who would need to be alerted and by what mechanism
- [ ] UX Support -- Is every step intuitive, clear, and is the purpose and value understandable for the user?
- [ ] Org Support -- Do Coaches and Staff have what they need to connect families, support their different needs, and see progress?

### Dependencies
This ticket is part of an epic-level effort happening on the Salesforce and Coach App level including:
- Coach Checklists
- Record QA automation
- Enrollment Solutions (Coach App and Coach Flow for Student Reg)
- Site Manager Solutions (Enrollment and record status)
- Paper Workflow Support
- Record "Completeness Monitoring"

### Milestone
https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/milestone/3

**Comment by CritiqalPete** [comment]
@AleksandrMolchagin is connecting Slack. Let's do some testing around the message content to close this out.
